### ISSUE TITLE
internal/errors:497

### ISSUE THREAD

**Issue by shayfer** [1thorsten/ewake#16]
Installed on multiple host docker environments to verify issue. While host is running if I click any of the options.

[show active clients](http://192.168.1.xx:5555/activeClients)
[show internal logs](http://192.168.1.xx:5555/check)
[show ip address and mac address of the requesting host](http://192.168.1.xx:5555/clientInfo)

The host server docker container crashes. Networking is set to Host. Open ports are 5555 --> 5555. -V mapped to /opt/ewake --> /ewake-clients

Docker logs show. 

node:internal/errors:497
    ErrorCaptureStackTrace(err);
    ^
Error [ERR_HTTP_HEADERS_SENT]: Cannot write headers after they are sent to the client
    at new NodeError (node:internal/errors:406:5)
    at ServerResponse.writeHead (node:_http_server:345:11)
    at a.httpError (/ewake/ewake.js:2:54010)
    at Server.<anonymous> (/ewake/ewake.js:2:259856)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
Node.js v20.9.0

Thanks for any help!

**Comment by 1thorsten** [comment]
Good morning, I have fixed the sending of HTTP headers. Now the error should at least be displayed properly.

Can you please give me the complete logs of the application as well as your docker-compose.yml or the complete docker run command.

br
